using System;
using System.Collections.Generic;
using CluedIn.Core.Net.Mail;
using CluedIn.Core.Providers;

namespace CluedIn.Crawling.AzureDataLake.Core
{
    public class AzureDataLakeConstants
    {
        public struct KeyName
        {
            public const string ApiKey = nameof(ApiKey);
            public const string AccountName = nameof(AccountName);
            public const string BaseUrl = nameof(BaseUrl);
            public const string FolderName = nameof(FolderName);
            public const string FileName = nameof(FileName);

        }

        // TODO Complete the following section
        // Please see https://cluedin-io.github.io/CluedIn.Documentation/docs/1-Integration/build-integration.html
        public const string CrawlerDescription = "AzureDataLake is a ... to be completed ...";
        public const string Instructions = "Provide authentication instructions here, if applicable";
        public const IntegrationType Type = IntegrationType.Cloud;
        public const string Uri = "http://www.sampleurl.com"; //Uri of remote tool if applicable

        // To change the icon see embedded resource
        // src\AzureDataLake.Provider\Resources\cluedin.png
        public const string IconResourceName = "Resources.cluedin.png";

        public static IList<string> ServiceType = new List<string> { "" };
        public static IList<string> Aliases = new List<string> { "" };
        public const string Category = "";
        public const string Details = "";
        public static AuthMethods AuthMethods = new AuthMethods()
        {
            token = new Control[]
            {
                    new Control()
                    {
                        displayName = "API key",
                        isRequired = true,
                        name = "ApiKey",
                        type = "password"
                    },
                    new Control()
                    {
                        displayName = "Account Name",
                        isRequired = true,
                        name = "AccountName",
                        type = "text"
                    }
                    ,
                    new Control()
                    {
                        displayName = "Base Url",
                        isRequired = true,
                        name = "BaseUrl",
                        type = "text"
                    }
                     ,
                    new Control()
                    {
                        displayName = "Folder Name",
                        isRequired = true,
                        name = "FolderName",
                        type = "text"
                    }
                     ,
                    new Control()
                    {
                        displayName = "File Name",
                        isRequired = true,
                        name = "FileName",
                        type = "text"
                    }

            }
        };


        public const bool SupportsConfiguration = true;
        public const bool SupportsWebHooks = false;
        public const bool SupportsAutomaticWebhookCreation = true;

        public const bool RequiresAppInstall = false;
        public const string AppInstallUrl = null;
        public const string ReAuthEndpoint = null;

        #region Autogenerated constants
        public const string CodeOrigin = "AzureDataLake";
        public const string ProviderRootCodeValue = "AzureDataLake";
        public const string CrawlerName = "AzureDataLakeCrawler";
        public const string CrawlerComponentName = "AzureDataLakeCrawler";
        public static readonly Guid ProviderId = Guid.Parse("c8057fa3-9253-4b7c-b167-ba1d4ffa0ca9");
        public const string ProviderName = "AzureDataLake";

        


        public static readonly ComponentEmailDetails ComponentEmailDetails = new ComponentEmailDetails
        {
            Features = new Dictionary<string, string>
            {
                                       { "Tracking",        "Expenses and Invoices against customers" },
                                       { "Intelligence",    "Aggregate types of invoices and expenses against customers and companies." }
                                   },
            Icon = ProviderIconFactory.CreateConnectorUri(ProviderId),
            ProviderName = ProviderName,
            ProviderId = ProviderId,
            Webhooks = SupportsWebHooks
        };

        public static IProviderMetadata CreateProviderMetadata()
        {
            return new ProviderMetadata
            {
                Id = ProviderId,
                ComponentName = CrawlerName,
                Name = ProviderName,
                Type = Type.ToString(),
                SupportsConfiguration = SupportsConfiguration,
                SupportsWebHooks = SupportsWebHooks,
                SupportsAutomaticWebhookCreation = SupportsAutomaticWebhookCreation,
                RequiresAppInstall = RequiresAppInstall,
                AppInstallUrl = AppInstallUrl,
                ReAuthEndpoint = ReAuthEndpoint,
                ComponentEmailDetails = ComponentEmailDetails
            };
        }
        #endregion
    }
}
